# Generated by Django 5.2 on 2025-05-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shonchoy', '0003_webpage_remove_loan_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='installments',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
