# Generated by Django 5.2 on 2025-05-02 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shonchoy', '0004_loan_installments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('INSTALLMENT_DUE', 'Installment Due'), ('LOAN_DUE', 'Loan Due'), ('DEPOSIT', 'Deposit'), ('CASH_OUT', 'Cash Out')], max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shonchoy.memberprofile')),
                ('related_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shonchoy.loan')),
            ],
        ),
    ]
